namespace adapter_interface;

public interface IMessageAdapter
{
    string Name { get; }
    string UpperName { get; }
    string LowerSnakeName { get; }
    List<IMemberAdapter> Members { get; }
    int MembersCount { get; }
    List<IMemberAdapter> ArrayMembers { get; }
    List<IMemberAdapter> NonArrayMembers { get; }
    bool HasArrayMember { get; }
    bool HasMessageTypeMember { get; }
    List<IMessageAdapter> DependentMessages { get; }
    bool HasDependentMessages { get; }
    List<IMessageAdapter> MessageTypeDependencies { get; }
    bool HasEnumTypeMember { get; }
    bool HasMembers { get; }
    bool HasFileTimeMembers { get; }
    List<IMemberAdapter> FileTimeMembers { get; }
    string PlainName { get; }
    bool HasDefine { get; }
    IDefineAdapter Define { get; }
    bool HasNumericDefine { get; }
    string PreprocessorDefineId { get; }
    int DefineId { get; }
    bool HasSiteIdMember { get; }
    List<IMemberAdapter> SiteIdMember { get; }
    bool HasCssSiteIdMember { get; }
    List<IMemberAdapter> CssSiteIdMember { get; }
    bool HasCardIdMember { get; }
    List<IMemberAdapter> CardIdMember { get; }
    bool HasEgmSerialNumberMember { get; }
    List<IMemberAdapter?> EgmSerialNumberMember { get; }
    bool HasDateMember { get; }
    bool HasVariableLengthArrayMember { get; }
    bool HasVariableLengthArraySizeMember { get; }
    IMemberAdapter VariableLengthArrayMember { get; }
    IMemberAdapter AnyVariableLengthArrayMember { get; }
    List<IMemberAdapter> VariableLengthArrayMemberPath { get; }
    List<IMemberAdapter> VariableLengthArraySizeMemberPath { get; }
    bool HasMemberWithVariableLengthArrayMember { get; }
    IMemberAdapter MemberWithVariableLengthArrayMember { get; }
    List<IMessageAdapter> TypeDependencies { get; }
    List<IEnumAdapter> EnumDependencies { get; }
    bool HasStrippedNameMemberClash { get; }
    int MessageByteSize { get; }
    string PointerType { get; }
    string GenerateDate { get; }
    string WabFilter { get; }
    bool IsHOSTFilter { get; }
    bool HasHOSTMemberFilter { get; }
    string HOSTMemberFilter { get; }
    string DartClassFileName { get; }
    int HOSTMemberOffset { get; }
    int HOSTMemberByteSize { get; }
    bool IsSITEFilter { get; }
    bool HasSITEMemberFilter { get; }
    string SITEMemberFilter { get; }
    int SITEMemberOffset { get; }
    int SITEMemberByteSize { get; }
    string Description { get; }
    string ExtendedDescription { get; }
    string Category { get; }
    string Generator { get; }
    string Consumer { get; }
    string AlertLevel { get; }
    string Reason { get; }
    bool IsEmptyMessage { get; }
    bool IsNonMessage { get; }
    string JavaClassFileName { get; }
    string JavaInterfaceFileName { get; }
    string JavaClassName { get; }
    string JavaInterfaceName { get; }
    List<IDefineAdapter> MemberDefines { get; }
    bool HasGeneratedMessages { get; }
    List<IMessageAdapter> GeneratedMessages { get; }
    bool HasTraceMembers { get; }
    List<string> TraceMemberValuePaths { get; }
    bool HasExternalKey { get; }
    IExternalKeyAdapter ExternalKeyAdapter { get; }
    bool HasAdditionalAttribute { get; }
    string AdditionalAttribute { get; }
    List<TraceAssociation>? TraceMembers { get; }
    ExternalKeyGenerator? ExternalKey { get; }
    List<IMemberPathAdapter> TraceMemberPaths { get; }
}
